version: '3.0'

services:
  cfb-app:
    image: 'cfb_img:latest'
    build:
      context: ..
    container_name: cfb
    ports:
      - "8080:8080"
    environment:
      - DISCORD_TOKEN=MTIyODA3MDY1NTIwODE5NDIwOA.GWeLBA.oJNK21qjvYpMxDvzYqtU0YVUpCxNH2-R9w9zxw